### PR TITLE
Fixes no profiles to merge error

### LINKED ISSUE #557: Error when no profile found to merge
Seems like if ingester have no profiles for the request we error but we should probably not:

```
unknown: no profiles to merge
```

### PR DESCRIPTION
**Pull request by cyriltovena**
Fixes grafana/phlare#557 

This was happening when the timerange was returning no queriers.

Also changed the TimeNanos to be from the end not the start.

### CODE REVIEW

File: pkg/model/profile.go [hunk 1]
```diff
@@ -45,3 +46,18 @@ func SelectorFromProfileType(profileType *typesv1.ProfileType) *labels.Matcher {
...
 	}
 }
+
+// SetProfileMetadata sets the metadata on the profile.
+func SetProfileMetadata(p *profile.Profile, ty *typesv1.ProfileType) {
+	p.SampleType = []*profile.ValueType{{Type: ty.SampleType, Unit: ty.SampleUnit}}
+	p.DefaultSampleType = ty.SampleType
+	p.PeriodType = &profile.ValueType{Type: ty.PeriodType, Unit: ty.PeriodUnit}
+	switch ty.Name {
+	case "process_cpu": // todo: this should support other types of cpu profiles
```
Comment (simonswine) [inline pkg/model/profile.go:56]: Should we create an issue for that?

**Review by simonswine — APPROVED** [review]
LGTM

File: pkg/model/profile.go (hunk 1 above)
Comment (cyriltovena) [reply pkg/model/profile.go:56]: I already did. https://github.com/grafana/phlare/issues/560
